name: chatdan_frontend
description: ChatDan 社区

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.10
  json_annotation: ^4.8.1
  provider: ^6.0.5
  dio: ^5.1.2
  go_router: ^7.1.1
  flutter_smart_dialog: ^4.9.0+6
  url_launcher: ^6.0.9
#  flutter_clipboard_manager: ^0.1.6
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  logging: 1.1.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

